# Generated by Django 5.0 on 2023-12-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepointapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestappointment',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requestappointment',
            name='email_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requestappointment',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requestappointment',
            name='service',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requestappointment',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
