# Generated by Django 5.0 on 2023-12-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepointapp', '0002_requestappointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestappointment',
            name='service',
            field=models.CharField(choices=[('Massage', 'Massage'), ('Waxing', 'Waxing'), ('Skincare', 'Skincare')], default='', max_length=50),
        ),
    ]
