# Generated by Django 5.0 on 2023-12-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepointapp', '0003_alter_requestappointment_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('email_address', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('service', models.CharField(choices=[('Massage', 'Massage'), ('Waxing', 'Waxing'), ('Skincare', 'Skincare'), ('Other', 'Other')], default='', max_length=50)),
                ('text_content', models.TextField(max_length=200)),
            ],
        ),
    ]
