# Generated by Django 5.0 on 2023-12-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitepointapp', '0004_messagerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('service', models.CharField(choices=[('Massage', 'Massage'), ('Waxing', 'Waxing'), ('Skincare', 'Skincare')], default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('time', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
